### PR TITLE
POC for build without mongodb

### LINKED ISSUE #161: Self-Signed Certificate Does Not Contain "Subject Alternative Name" field
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior
I expected the container release to generate a self-signed certificate in the same way the official Linux / Windows versions do, in that it would contain a "Subject Alternative Name" field with a value of "DNS Name=UniFi". 

The problem is that under Windows 11, even if self-signed certificates are properly installed in "Trusted Root Certification Authorities", web browsers will show a server's certificate as untrusted if the installed certificate lacks that "Subject Alternative Name" field. Some information regarding this can be found at [this link](https://blog.shafeeque.in/browser-not-trusting-self-signed-certificate-even-after-importing-into-the-trusted-root-certificate-folder/).

For small, local-use-only installs where self-signed certificates are appropriate, a user might wish to install that certificate locally to prevent annoying browser security pop-ups. Invalid certificates also prevent some web browsers from saving usernames and passwords.

## Current Behavior
The self-signed certificate that is generated does not contain a "Subject Alternative Name" field. 

## Steps to Reproduce

1. Spin up a new container
2. Load the UI in a web browser
3. Inspect the certificate
4. Notice the lack of a "Subject Alternative Name" field
5. Export the certificate
6. Under Windows 11, double-click the certificate and import into "Trusted Root Certification Authorities"
7. Add the appropriate entry for the server to `C:\Windows\System32\drivers\etc\hosts`
8. Restart web browsers
9. Open a web browser to the UniFi Network Controller and notice the certificate error
10. Repeat with an official install of the UniFi Network Controller and notice there is no certificate error

## Environment
**OS:** Ubuntu 22.10
**CPU architecture:** x86_64
**How docker service was installed:** `docker pull linuxserver/unifi-controller`

## Command used to create docker container (run/create/compose/screenshot)
Using the `docker-compose.yml` outlined at [hub.docker.com](https://hub.docker.com/r/linuxserver/unifi-controller#:~:text=docker%2Dcompose%20(recommended), changing only the `<path_to_data>`

### PR DESCRIPTION
**Pull request by thespad**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-unifi-controller/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
This needs solid testing.

Replaces https://github.com/linuxserver/docker-unifi-controller/pull/155
Closes #161

### CODE REVIEW

File: root/etc/s6-overlay/s6-rc.d/init-unifi-controller-config/run [hunk 1]
```diff
@@ -20,6 +20,11 @@ for i in "${symlinks[@]}"; do
 done
 
 if [[ ! -e /config/data/system.properties ]]; then
+    sed -i "s/~MONGO_USER~/${MONGO_USER}/" /defaults/system.properties
+    sed -i "s/~MONGO_PASS~/${MONGO_PASS}/" /defaults/system.properties
+    sed -i "s/~MONGO_HOST~/${MONGO_HOST}/" /defaults/system.properties
+    sed -i "s/~MONGO_PORT~/${MONGO_PORT}/" /defaults/system.properties
+    sed -i "s/~MONGO_DBNAME~/${MONGO_DBNAME}/" /defaults/system.properties
     cp /defaults/system.properties /config/data
 fi
```
Comment (Roxedus) [inline root/etc/s6-overlay/s6-rc.d/init-unifi-controller-config/run:29]: Worth mentioning in the readme that the variables are only read on a clean install, if we aren't going to modify the live file.

Comment (thespad) [reply root/etc/s6-overlay/s6-rc.d/init-unifi-controller-config/run:29]: It says in the variable description https://github.com/linuxserver/docker-unifi-controller/pull/197/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R193

Comment (Roxedus) [reply root/etc/s6-overlay/s6-rc.d/init-unifi-controller-config/run:29]: protip: dont read PRs the first 15 minutes after waking up

**Review by Roxedus — APPROVED** [review]
